# Copyright (c) The OpenTofu Authors
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2023 HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "2"

# We intentionally use golangci-lint's default settings, under the assumption
# that this project curates a reasonable baseline of lint rules.
